---
title: "A story of te US American honeybee"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    theme: sandstone
    logo: www/honigbiene.png
    favicon: favicon.png
    runtime: shiny
---

    
```{r Libraries, message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(ggplot2)
library(knitr)
library(cowplot)
library(RColorBrewer)
library(measurements)
library(dygraphs)
library(flexdashboard)
#colorbrewer palette YlOrBr
```
Bee interactive!
Fly through the story and discover the story of the bees!
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
honeyproduction <- read.csv(file="honeyproduction.csv", header=TRUE, sep=",")

#Umrechnen von Pfund in Kilogramm
honeyproduction <- honeyproduction %>% 
  mutate(yieldpercol_kg = conv_unit(yieldpercol, "lbs", "kg"),
         price_per_kg = priceperlb / conv_unit(1, "lbs", "kg"),
         totalprod_kg = conv_unit(totalprod, "lbs", "kg")
         )
#nomissing values 
#colSums(is.na(honeyproduction))
```

```{r}
#pesticides dataframe
pesticides <- read.csv(file="vHoneyNeonic_v03.csv", header=TRUE, sep=",")
#Umrechnen von Pfund in Kilogramm
pesticides <- pesticides %>% 
  mutate(yieldpercol_kg = conv_unit(yieldpercol, "lbs", "kg"),
         price_per_kg = priceperlb / conv_unit(1, "lbs", "kg"),
         totalprod_kg = conv_unit(totalprod, "lbs", "kg"),
         nAllNeonic_kg = conv_unit(nAllNeonic, "lbs", "kg")
         )
```


```{r}
# total_production <- merge(honeyproduction, pesticides, by=c("state", "numcol", "stocks", "price_per_kg", "prodvalue", "year", "yieldpercol_kg", "price_per_kg", "total_prod"))


total_production <- bind_rows(honeyproduction, pesticides) 

#remove duplicates by deleting missing N.A. row (region)
total_production <- total_production[!is.na(total_production$Region), ]

```

```{r data_beeimages}
# beeimages
bee_data <- read.csv(file="bee_data.csv", header=TRUE, sep=",")
```
### The Problem of the Honeybee
```{r echo=FALSE, message=FALSE, warning=FALSE}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)

```

#Column {.sidebar}
#-----------------------------------------------------------------------
```{r}
renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser Eruption Duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```


### Bees - information beehind


```{r}
#hier infos über die biene
```



### Where did all the honey go?

```{r}
honeyyear <- honeyproduction %>%
  group_by(year) %>%
  summarise(YearTotal=sum(totalprod))
ggplot(data=honeyyear, aes(x=year, y=YearTotal/1000000, title="How much Honey did the USA produce between 1998 and 2012?")) + 
  geom_smooth(method = "lm") + 
  geom_line(color = "#f3a328", size = 2) +
  geom_point() +
  scale_x_continuous(breaks=seq(1998, 2012, 1)) +
  ylab("Million kg Honey produced") +
  xlab("years") +
  theme_bw()+
  background_grid(major = "xy", minor="y", size.major = 0.2) 
```


### Frame 4


```{r}
honeyperstate <- honeyproduction %>%
    group_by(state) %>%
    summarise(sumprod=sum(totalprod)) %>%
    arrange(sumprod) %>%
    mutate(percentage=round(sumprod/sum(sumprod)*100,2)) %>% 
    top_n(10)
    
ggplot(data=honeyperstate,
          aes(
              x=reorder(state,sumprod),
              y=sumprod/1000000
          )
       )+
       geom_col(aes(fill=state),show.legend=F)+
       geom_text(aes(label=percentage))+
       coord_flip()+
       labs(x="states of the USA",y="total honey produced (in million kg)",title="In which state were the honeybees most diligent?")  +
       background_grid(major = "xy", minor="y", size.major = 0.2) 
```


### Frame 5

```{r}
pesticides_year_production <- pesticides %>%
  group_by(year) %>%
  summarise(production_year=sum(totalprod_kg))

pesticides_year_neonics <- pesticides %>% 
  na.omit(nAllNeonic) %>% 
  group_by(year) %>% 
  summarise(neonics_year=sum(nAllNeonic))

pesticides_year_total <- merge(pesticides_year_production, pesticides_year_neonics)

ggplot(data=pesticides_year_total, aes(x = year)) + 
  geom_line(aes(y = production_year, colour = "Honey")) + 
  geom_line(aes(y = neonics_year*30, colour = "Neonic Pesticides")) + 
  scale_y_continuous(breaks=c(0, 10000000, 20000000, 30000000, 40000000, 50000000, 60000000, 70000000, 80000000, 90000000, 100000000), labels=c("0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"), sec.axis = sec_axis(~./30, name = "Amount of neonic pesticides applied in the US [million kg]", breaks=c(0, 500000, 1000000, 1500000, 2000000, 2500000, 3000000, 3500000), labels=c("0", "0,5", "1", "1,5", "2", "2,5", "3", "3,5"))) +
  geom_point(aes(y = production_year, colour = "Honey")) + 
  geom_point(aes(y = neonics_year*30, colour = "Neonic Pesticides")) +
  scale_colour_manual(values = c("cyan", "magenta")) + 
  labs(y = "Amount of honey produced in the US [million kg]", x = "Year", colour = "Parameter") +
  theme_bw()
```