---
title: "Bee_HTML"
author: "Anne Vollema"
date: "26 6 2019"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(knitr)
library(cowplot)
library(RColorBrewer)
library(measurements)
#colorbrewer palette YlOrBr
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
honeyproduction <- read.csv(file="honeyproduction.csv", header=TRUE, sep=",")

#Umrechnen von Pfund in Kilogramm
honeyproduction <- honeyproduction %>% 
  mutate(yieldpercol_kg = conv_unit(yieldpercol, "lbs", "kg"),
         price_per_kg = priceperlb / conv_unit(1, "lbs", "kg"),
         totalprod_kg = conv_unit(totalprod, "lbs", "kg")
         )
#nomissing values 
#colSums(is.na(honeyproduction))
```

```{r}
#pesticides dataframe
pesticides <- read.csv(file="vHoneyNeonic_v03.csv", header=TRUE, sep=",")
#Umrechnen von Pfund in Kilogramm
pesticides <- pesticides %>% 
  mutate(yieldpercol_kg = conv_unit(yieldpercol, "lbs", "kg"),
         price_per_kg = priceperlb / conv_unit(1, "lbs", "kg"),
         totalprod_kg = conv_unit(totalprod, "lbs", "kg")
         )
```

#merge

```{r}
# total_production <- merge(honeyproduction, pesticides, by=c("state", "numcol", "stocks", "price_per_kg", "prodvalue", "year", "yieldpercol_kg", "price_per_kg", "total_prod"))


total_production <- bind_rows(honeyproduction, pesticides) 

#remove duplicates by deleting missing N.A. row (region)
total_production <- total_production[!is.na(total_production$Region), ]
```

```{r cars}
summary(honeyproduction)
```

Honeyproduction from 1998-2012
```{r}
##hier muss total_production eigentlich rein aber dann macht es komische sachen mit den years
honeyyear <- total_production %>%
  group_by(year) %>%
  summarise(YearTotal=sum(totalprod_kg))
ggplot(data=honeyyear, aes(x=year, y=YearTotal/1000000, title="How much Honey did the USA produce between 1998 and 2012?")) + 
  geom_smooth(method = "lm") + 
  geom_line(color = "#f3a328", size = 2) +
  geom_point() +
  scale_x_continuous(breaks=seq(1998, 2012, 1)) +
  ylab("Million kg of produced honey") +
  xlab("years") +
  theme_bw()+
  background_grid(major = "xy", minor="y", size.major = 0.2) 
```

```{r}
ggplot(data=total_production, aes(x=numcol, y=totalprod_kg/100000, title = "titel")) + 
  geom_smooth(method = "lm") + 
  geom_line(color = "#f3a328", size = 2) +
  geom_point() +
  scale_x_continuous(breaks=seq(1998, 2012, 1)) +
  ylab("number of honeyproducing colonies per State") +
  xlab("total production (in kg)") +
  theme_bw()+
  background_grid(major = "xy", minor="y", size.major = 0.2)
```

The North-Dakota bees were the most busy bees. North Dakota produced 16,83% from the US-honey in total.
```{r}
honeyperstate <- total_production %>%
    group_by(state) %>%
    summarise(sumprod=sum(totalprod_kg)) %>%
    arrange(sumprod) %>%
    mutate(percentage=round(sumprod/sum(sumprod)*100,2)) %>% 
    top_n(10)
    
ggplot(data=honeyperstate,
          aes(
              x=reorder(state,sumprod),
              y=sumprod/1000000
          )
       )+
       geom_col(aes(fill=state),show.legend=F)+
       geom_text(aes(label=percentage))+
       coord_flip()+
       labs(x="states of the USA",y="Percentage of US-honey",title="In which state were the honeybees most diligent?")  +
       background_grid(major = "xy", minor="y", size.major = 0.2) 
```





```{r}
pesticides_clean <- na.omit(total_production)

pesticides_year <- pesticides_clean %>%
  group_by(year) %>%
  summarise(production_year=sum(totalprod_kg))

pesticides_year2 <- pesticides_clean %>% 
  group_by(year) %>% 
  summarise(neonics_year=sum(nAllNeonic))

pesticides_year_total <- merge(pesticides_year, pesticides_year2)

ggplot(data=pesticides_year_total, aes(year)) +
  geom_line(aes(y=production_year)) +
  geom_line(aes(y=neonics_year)) +
  theme_bw()
```






##### hier wolte ich was ausprobieren

```{r}
library(plotly)
library(quantmod)

getSymbols("AAPL",src='yahoo')

total_production_map <- total_production(Date=index(AAPL),coredata(AAPL))
total_production_map <- tail(total_production, 30)
total_production_map$ID <- seq.int(nrow(total_production_map))

accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}

total_production_map <- total_production_map %>%
  accumulate_by(~price_per_kg)

p <- total_production_map %>%
  plot_ly(
    x = ~year, 
    y = ~price_per_kg, 
    frame = ~frame,
    type = 'scatter', 
    mode = 'lines', 
    fill = 'tozeroy', 
    fillcolor='rgba(114, 186, 59, 0.5)',
    line = list(color = 'rgb(114, 186, 59)'),
    text = ~paste("Year: ", year, "<br>Price per kg in $", price_per_kg), 
    hoverinfo = 'text'
  ) %>%
  layout(
    title = "Price year 1992-2017",
    yaxis = list(
      title = "Price", 
      range = c(1992,2017), 
      zeroline = F,
      tickprefix = "$"
    ),
    xaxis = list(
      title = "Year", 
      range = c(1992,2017), 
      zeroline = F, 
      showgrid = F
    )
  ) %>% 
  animation_opts(
    frame = 100, 
    transition = 0, 
    redraw = FALSE
  ) %>%
  animation_slider(
    currentvalue = list(
      prefix = "Year"
    )
  )

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
#chart_link = api_create(p, filename="cumAnimations-filled-area")
#chart_link
```


```{r}
accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}


plotlyplot1 <- total_production %>%
  plot_ly(
    x = ~year, 
    y = ~price_per_kg,
    split = ~state,
    frame = ~frame, 
    type = 'scatter',
    mode = 'lines', 
    line = list(simplyfy = F)
  ) %>% 
  layout(
    xaxis = list(
      title = "Year",
      zeroline = F
    ),
    yaxis = list(
      title = "Honeyprice per kg",
      zeroline = F
    )
  ) %>% 
  animation_opts(
    frame = 100, 
    transition = 0, 
    redraw = FALSE
  ) %>%
  animation_slider(
    hide = T
    ) %>%
  animation_button(
    x = 1, xanchor = "right", y = 0, yanchor = "bottom"
  )
```

